### ISSUE TITLE
Issue with blocking - missing check?

### ISSUE THREAD

**Issue by lukasm91** [GridTools/gridtools#1204]
It is forbidden to have "real inout-accessors" (i.e., neither in, nor out, but *real* inout, such as `eval(inout()) = 2 * eval(inout())`) in any stage that has non-zero extent, because those functors might be evaluated several times (1, 2 or 4 times) when we do blocking.

An example in more detail (note that I copied the example from the copy example - not all comments are updated):
https://github.com/eth-cscs/gridtools/compare/master...lukasm91:issue_with_extents

This example passes for x86-naive backend (because we don't use blocking). It fails for the other backends.

It's clear that the examples fail, because the stencil is applied twice to the edges of the block and four times to the corners of the block. And as this is quite a fundamental restriction, I assume that this needs to be forbidden. Is it worth to add a check? I think for a user that might help a lot, because to a naive user, it looks like this test "randomly" fails on certain platforms and for certain sizes.

The cuda tests fail too for larger domains (as soon as not all threads run concurrently anymore).

**Comment by havogt** [comment]
This example is now forbidden by access restriction 4a

>4. A stage may read from an accessor and write to it in a later statement, if
>
>    a. all reads of this accessor are in stages where the compute domain is not extended;

See #1541.
