### ISSUE TITLE
Performance regression in CUDA 9.2

### ISSUE THREAD

**Issue by havogt** [GridTools/gridtools#1223]
This issue is to keep track of the performance degradation from CUDA 9.1 to CUDA 9.2.

**Comment by lukasm91** [comment]
There seems to be a workaround for the problems in the vertical stencils, but the problem for horizontal diffusion fused remains.

A minimal reproducible example has been created and submitted through webrt.
https://webrt.cscs.ch/SelfService/Display.html?id=35640&results=42c82c213adfee3838179805c967791c

**Comment by lukasm91** [comment]
The problem occurs when returning references from constexpr functions in some nested way. Cray has reproduced the issue.

**Comment by havogt** [comment]
Workarounds where implemented in #1281.
