### ISSUE TITLE
Invalid results / crashes on daint in GCL

### ISSUE THREAD

**Issue by lukasm91** [GridTools/gridtools#1236]
On Piz Daint, the node crashes when using the same GPU pointer twice for MPI Communications, when freeing and reallocating between. The bug is most likely in Cray's MPI implementation. A bug report is filed with Cray.

https://webrt.cscs.ch/SelfService/Display.html?id=35371&results=80f2c1a6c1a25a1e0803a6f109a726bb

Thus, we cannot free CUDA memory in GCL, because otherwise we might get the same pointer again. This either leads to incorrect results, or crashes the node.

**Comment by havogt** [comment]
Cray was able to reproduce the issue.

**Comment by fthaler** [comment]
Are there any news from Cray on this? If yes, we could fix the memory leak…

**Comment by havogt** [comment]
The Cray case is still open, no news.

**Comment by havogt** [comment]
No updates, cray case #236477.
