### ISSUE TITLE
StorageInfo leak in boundary conditions

### ISSUE THREAD

**Issue by havogt** [GridTools/gridtools#1237]
The boundary conditions still create cuda views and therefore still have the problem of #652, i.e. leaking 8 bytes per view.

**Comment by fthaler** [comment]
What’s again the reason of not just copying the storage info to the device each time? At least in GT 2/master a `info<3>` object is only 28 bytes (if I counted correctly). So we only save roughly 20B×(N - 1), where N is the number of views used in a kernel, that’s not a lot in the usual cases I guess? Further directly copying might improve usage of constant cache, who knows.
