### ISSUE TITLE
Inconsistency between total_length<masked_dim>()  multiplied and total_length()

### ISSUE THREAD

**Issue by havogt** [GridTools/gridtools#1368]
If we construct a storage_info with a masked dimension and pass a size != 1, we store it.
`total_length()` without dimension gives the correct size, i.e. not taking into account the masked dimension. `total_length<dim>()` and colleagues don't take masking into account.

2 possible solutions:
- set size of a masked dimension to 1 in the constructor.
- change `total_length<dim>()` and colleagues to return 1.

**Comment by havogt** [comment]
Should be backported to `release_v1.0` and `release_1.1`

**Comment by havogt** [comment]
@fthaler and I came to the conclusion that in any case we will have an inconsistency and therefore it makes more sense to clean this completely by removing the masking (which is not a concept of storage, but of stencil-composition).

**Comment by anstaf** [comment]
resolved in 2.0
