### ISSUE TITLE
Exporting OpenMP seems wrong

### ISSUE THREAD

**Issue by mbianco** [GridTools/gridtools#1375]
In line https://github.com/GridTools/gridtools/blob/4c9a877fcac5441b5ef2ce114ff8c75f7212e917/cmake/definitions.cmake#L37
it looks like the flags for OpenMP are exported, but I think this is wrong. I our development we need to test openmp and std::thread implementations, and we would like to use std::threads if openmo is not used (compilation without -fopenmp), but it is always included in the compilation of our targets even though our tests do not use it. would it make sense to remove the flag in dependent projects?

**Comment by wdeconinck** [comment]
See also https://github.com/GridTools/gridtools/pull/1359

**Comment by havogt** [comment]
I agree. I propose we export a target for each architecture which carries the relevant flags.

**Comment by havogt** [comment]
Fixed in #1421
