### ISSUE TITLE
Request for Example: Fortran+CUDA

### ISSUE THREAD

**Issue by AndiH** [GridTools/gridtools#1403]
We are preparing a hands-on example for our [ESM User Forum](https://www.fz-juelich.de/SharedDocs/Termine/IAS/JSC/EN/courses/2020/esm-user-forum-2020.html) in a few days and want to show usage of GridTools for that occasion.

We would like to use the Fortran binding capabilities to launch a GridTools 2D Jacobi stencil on the GPU.

As a GridTools newbie, I lack an example, showing Fortran usage of GPU GridTools stencils. I found the [`driver.f90` of the `c_bindings`](https://github.com/GridTools/gridtools/blob/master/examples/c_bindings/driver.f90) example, but that uses the MC backend. Is there one which I overlooked? Or can you quickly put something together which I can use as a blueprint?

We intend to use either GCC as our host compiler or PGI (we are showing an OpenACC stencil as well).

**Comment by mbianco** [comment]
Dear @AndiH As far as I remember this should be just matter of allocating the data on the GPU and then passing GPUs pointers to the computations (and compile with the GPU backend).  We'll get back to you with more specific information.

**Comment by AndiH** [comment]
Thanks for the swift reply!

Exactly, that's what I haven't cleared up yet in my head: How to allocate GPU buffers. Most probably I should do that within the wrapped GridTools C++ file, since that is already compiled with `nvcc`. Then we wouldn't need to add further Fortran bindings to `cudaMalloc[Managed]`.

**Comment by AndiH** [comment]
Any news on this, @mbianco? Otherwise we'd need to work on an alternative plan for our hands-ons.

**Comment by mbianco** [comment]
Hi @AndiH , we are looking in this, but we cannot guarantee the time right now, since our bandwidth is limited. We want to make the example nice and be included in the repo and the documentation

**Comment by AndiH** [comment]
I understand. That cut's it quite close for us. We might try to whip something up ourselves. Might I email you for some feedback once we have a sketch?

**Comment by mbianco** [comment]
Sure!

**Comment by havogt** [comment]
You can also join the GridTools slack channel for discussion. https://gridtools-slack.herokuapp.com/

**Comment by havogt** [comment]
Need to port #1406 to master before v2.0 or out-source to cpp_bindgen.
