### ISSUE TITLE
Binding label bindgen_release in interface body at (1) collides

### ISSUE THREAD

**Issue by puneet336** [GridTools/gridtools#1407]
Hi,
I am trying to compile gridtools using instructions at - https://gridtools.github.io/gridtools/latest/introduction/introduction.html#installation-and-use
using gcc 7.2.0 , cuda10.0 and openmpi 3.1.4
configure stage was fine, but 

the make fails with following error - 
`[ 21%] Building Fortran object regression/c_bindings/CMakeFiles/cpp_bindgen_fortran_handle.dir/__/__/_deps/cpp_bindgen-src/src/cpp_bindgen/handle.f90.o
cd /home/user/GRIDTOOLS/master/src/gridtools/build/regression/c_bindings && /usr/bin/f95 -DBOOST_PP_VARIADICS=1 -DCPP_BINDGEN_GT_LEGACY -I/home/user/GRIDTOOLS/master/src/gridtools/build/_deps/cpp_bindgen-src/include  -J../../cpp_bindgen_modules   -cpp -c /home/user/GRIDTOOLS/master/src/gridtools/build/_deps/cpp_bindgen-src/src/cpp_bindgen/handle.f90 -o CMakeFiles/cpp_bindgen_fortran_handle.dir/__/__/_deps/cpp_bindgen-src/src/cpp_bindgen/handle.f90.o
/home/user/GRIDTOOLS/master/src/gridtools/build/_deps/cpp_bindgen-src/src/cpp_bindgen/handle.f90:12.34:
subroutine bindgen_release(h) bind(c)
`
`Error: Binding label 'bindgen_release' in interface body at (1) collides with the global entity 'bindgen_release' at (2)
make[2]: *** [regression/c_bindings/CMakeFiles/cpp_bindgen_fortran_handle.dir/__/__/_deps/cpp_bindgen-src/src/cpp_bindgen/handle.f90.o] Error 1`

Could you please help?
Please let me know if  more information is required from my end.

**Comment by havogt** [comment]
Which version of GridTools are you trying?

**Comment by puneet336** [comment]
Hi,
checked out gridtools using 
`git clone http://github.com/eth-cscs/gridtools.git`

seems version is 2.0.0 - 
```
[user@node1 gridtools]$ cat version.txt
2.0.0

```

**Comment by havogt** [comment]
This is the current development branch. Please try v1.1.3 by doing
```
git checkout v1.1.3
```
and do a fresh configure/build (delete the old build directory).
Most likely you will run into the same issue, but just to be sure.

**Comment by puneet336** [comment]
Hi, got same issue - 

[ 18%] Building Fortran object regression/c_bindings/CMakeFiles/cpp_bindgen_fortran_handle.dir/__/__/_deps/cpp_bindgen-src/src/cpp_bindgen/handle.f90.o
cd /home/puneet/MyWork/03022020/GRIDTOOLS/1.1.3_gnu/src/gridtools-1.1.3/build/regression/c_bindings && /usr/bin/f95 -DBOOST_PP_VARIADICS=1 -DCPP_BINDGEN_GT_LEGACY -I/home/puneet/MyWork/03022020/GRIDTOOLS/1.1.3_gnu/src/gridtools-1.1.3/build/_deps/cpp_bindgen-src/include  -J../../cpp_bindgen_modules   -cpp -c /home/puneet/MyWork/03022020/GRIDTOOLS/1.1.3_gnu/src/gridtools-1.1.3/build/_deps/cpp_bindgen-src/src/cpp_bindgen/handle.f90 -o CMakeFiles/cpp_bindgen_fortran_handle.dir/__/__/_deps/cpp_bindgen-src/src/cpp_bindgen/handle.f90.o
/home/puneet/MyWork/03022020/GRIDTOOLS/1.1.3_gnu/src/gridtools-1.1.3/build/_deps/cpp_bindgen-src/src/cpp_bindgen/handle.f90:24.29:

        subroutine gt_release(h) bind(c, name="bindgen_release")
                             1
/home/puneet/MyWork/03022020/GRIDTOOLS/1.1.3_gnu/src/gridtools-1.1.3/build/_deps/cpp_bindgen-src/src/cpp_bindgen/handle.f90:12.34:

        subroutine bindgen_release(h) bind(c)
                                  2
Error: Binding label 'bindgen_release' in interface body at (1) collides with the global entity 'bindgen_release' at (2)
make[2]: *** [regression/c_bindings/CMakeFiles/cpp_bindgen_fortran_handle.dir/__/__/_deps/cpp_bindgen-src/src/cpp_bindgen/handle.f90.o] Error 1
make[2]: Leaving directory `/home/puneet/MyWork/03022020/GRIDTOOLS/1.1.3_gnu/src/gridtools-1.1.3/build'
make[1]: *** [regression/c_bindings/CMakeFiles/cpp_bindgen_fortran_handle.dir/all] Error 2
make[1]: Leaving directory `/home/puneet/MyWork/03022020/GRIDTOOLS/1.1.3_gnu/src/gridtools-1.1.3/build'
make: *** [all] Error 2

**Comment by havogt** [comment]
For debugging could you provide the output of the CMake configure step? Thanks!

As a workaround:
What part of GridTools did you want to try? The failing part is only the Fortran bindings. In case you are for now not interested in this part I could provide the instructions to disable them.

**Comment by puneet336** [comment]
Here is the configure log,  and I am installing it at a shared location (to be used by other users).
Need to check if they require binaries which involve fortran codes.
`
-- The CXX compiler identification is GNU 7.2.0
-- Check for working CXX compiler: /cm/local/apps/gcc/7.2.0/bin/c++
-- Check for working CXX compiler: /cm/local/apps/gcc/7.2.0/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The CUDA compiler identification is NVIDIA 10.0.130
-- Check for working CUDA compiler: /cm/shared/apps/cuda10.0/toolkit/10.0.130/bin/nvcc
-- Check for working CUDA compiler: /cm/shared/apps/cuda10.0/toolkit/10.0.130/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- CUDA found
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5") found components: CXX
-- OpenMP found
-- Found MPI_CXX: /home/frank/apps/openmpi/3.1.4/lib/libmpi.so (found version "3.1")
-- Found MPI: TRUE (found version "3.1") found components: CXX
-- MPI found
-- Found Boost: /home/puneet/MySoftwares/UTILS/BOOST/1.72.0_gcc720/lib/cmake/Boost-1.72.0/BoostConfig.cmake (found suitable version "1.72.0", minimum required is "1.58")
-- Compile tests in double precision
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.5") found components: doxygen dot
-- Looking for a C compiler
-- Looking for a C compiler - /usr/bin/cc
-- The C compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for a Fortran compiler
-- Looking for a Fortran compiler - /usr/bin/f95
-- The Fortran compiler identification is GNU 4.8.5
-- Check for working Fortran compiler: /usr/bin/f95
-- Check for working Fortran compiler: /usr/bin/f95  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/bin/f95 supports Fortran 90
-- Checking whether /usr/bin/f95 supports Fortran 90 -- yes
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE
-- Found PythonInterp: /usr/bin/python (found version "2.7.5")
-- clang-tidy not found
-- clang-format not found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/MyWork/03022020/GRIDTOOLS/1.1.3_gnu/src/gridtools-1.1.3/build
`

**Comment by havogt** [comment]
The problem is you did not properly load the GNU toolchain. You are using 4.8.5 as Fortran and C compiler. Using gfortran 7.2, as you do for g++, should fix the issue.

**Comment by puneet336** [comment]
thanks , 
it seems that --enable-languages=c switch was used for gcc-7.2.0 compilation (was able to compile succesfully using gcc 9).

"/usr/bin/f95" was the giveaway which i missed in the logs!
Thank you for the prompt help, closing this issue.
