### ISSUE TITLE
Move fortran_array_adaptor and view to cpp_bindgen

### ISSUE THREAD

**Issue by havogt** [GridTools/gridtools#1415]
The Fortran array adaptor for gridtools data_stores is not well placed in the GridTools sources as it is not usable without cpp_bindgen. Similar it is not ideal in cpp_bindgen, since it needs gridtools::data_stores. 

The proposal is to add an `adapter` directory in cpp_bindgen where users of cpp_bindgen can place adapters for their storage (example, we could also put adapters for kokkos storages or atlas storages).

Once this is done, there is no dependency on cpp_bindgen and Fortran in the GridTools/gridtools repository anymore. Would automatically resolve #1412.

Depends on #1414

**Comment by havogt** [comment]
Maybe 2.0, maybe not.

**Comment by havogt** [comment]
We decided this will be kept in GridTools. Still we should probably move it to a different directory.

**Comment by havogt** [comment]
Should we move the adapters to `storage/adapters`?

**Comment by anstaf** [comment]
LGTM
And the SID adater as well?
