### ISSUE TITLE
Change backend names

### ISSUE THREAD

**Issue by havogt** [GridTools/gridtools#1419]
Users were confused by some of our backends, e.g.

- Can I use `x86` on a non x86 architecture?
- Why I use `mc` on an x86 architecture?
- cuda on hip?

TODO:
- [ ] don't forget to update documentation!

**Comment by fthaler** [comment]
Additional confusion will probably appear once we introduce a second CUDA/HIP backend for the horizontal stencils…

**Comment by mbianco** [comment]
What are the key differences in the x86 and mc backends in terms of architecture requirements for best performance? Can it have a simple name?

**Comment by havogt** [comment]
New proposal:
`cuda` -> `cuda`
new cuda aka `cuda2` -> `cuda_horizontal`
`x86` -> `cpu_kfirst`
`mc` -> `cpu_ifirst`

**Comment by vondele** [comment]
cuda -> acc ?
