### ISSUE TITLE
no matching constructor for initialization of 'array<typename _impl::make_array_helper

### ISSUE THREAD

**Issue by paklui** [GridTools/gridtools#1420]
Hello, I am running into some issue building GridTools. I noticed that missing constructor for ‘make_array_helper’, which is a template that appears to be coming from boost.
I tried to use the Ubuntu 18.04.4 build of boost that is 1.65 and the latest 1.72 which I built by hand, I tried to include differnent -DBoost_DIR and -DBoost_INCLUDE_DIR for cmake but it doesn’t appear to be taking them in CMakeCache.txt, so I needed some guidance to go forward. Thanks in advance for any guidance.
```
/home/paklui/gridtools-master/include/gridtools/tools/../common/tuple_util.hpp:1469:24: error: no matching constructor for initialization of 'array<typename _impl::make_array_helper<unsigned int, const unsigned long &, const unsigned long &, const int &>::type, sizeof...(Ts)>' (aka 'array<unsigned int, sizeof...(Ts)>')
                return {{implicit_cast<common_type_t>(wstd::forward<Ts>(elems))...}};
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by paklui** [comment]
some background info on the build script.
```
#!/bin/bash
export PATH=/opt/rocm/llvm/bin:${PATH}
export PATH=${HOME}/cmake-3.15.4-Linux-x86_64/bin:${PATH}
DATE=$(date +%y%m%d-%H%M%S)
LOG=log.boost-make-${DATE}.txt
rm -fr build
mkdir -p build && cd build
export CXX=/opt/rocm/bin/hipcc
cmake .. \
    -DBUILD_TESTING=ON \
    -DBoost_DIR=${HOME}/boost_1_72_0 \
    -DGT_CUDA_COMPILATION_TYPE=HIPCC-AMDGPU \
    -DGT_CUDA_ARCH="gfx906" \
    -DGT_ENABLE_BACKEND_CUDA=ON \
    -DGT_ENABLE_BACKEND_MC=OFF \
    -DGT_ENABLE_BACKEND_X86=OFF \
    -DGT_ENABLE_BACKEND_NAIVE=OFF \
    -DCMAKE_INSTALL_PREFIX=${HOME}/gridtools-master/install \
    -DMPI_CXX_ADDITIONAL_INCLUDE_DIRS=/opt/rocm/include \
    -DCMAKE_INSTALL_INCLUDEDIR=/opt/rocm/include \

make VERBOSE=1 2>&1 | tee -a $LOG
#make -j VERBOSE=1 install 2>&1 | tee -a $LOG
```

**Comment by mbianco** [comment]
Hi @paklui, we had issues with `hipcc` and we support hip-clang. What compiler are you using?
Also, the error does not show up in Boost but in GridTools `impl_` namespace. It could be useful to have the whole error message (if it's too long, limit the text to the text between the first two `error:` tokens, so we can see the chain of instantiations.

**Comment by havogt** [comment]
Additionally, the full output of CMake would be helpful (from the first CMake run on a clean build directory) as it will list versions of all dependencies.

**Comment by paklui** [comment]
I tried both hipcc and hip-clang. For hipcc this is the logs.
[log.gridtools-20200310.txt](https://github.com/GridTools/gridtools/files/4318563/log.gridtools-20200310.txt)

I include the CMakeCache.txt for hipcc here:
[grditools-CMakeCache.txt](https://github.com/GridTools/gridtools/files/4318512/grditools-CMakeCache.txt)

I started trying hip-clang but encountered some issues using the build.
[log.gridtools-clang-20200311.txt](https://github.com/GridTools/gridtools/files/4318583/log.gridtools-clang-20200311.txt)

**Comment by paklui** [comment]
sorry, forgot to mention that I made a change in cmake/definitions.cmake when I run hipcc:
     elseif(GT_CUDA_COMPILATION_TYPE STREQUAL "HIPCC-AMDGPU")
         set(hipcc_options_ -D__HIP_PLATFORM_HCC__ -I/opt/rocm/include ) #--amdgpu-target=gfx906)

For hip-clang run in my last comment, I forgot to set it back to this, so you can disregard my last message on hip-clang. 
         set(hipcc_options_ -xhip --amdgpu-target=${GT_CUDA_ARCH}) #hip-clang

I am trying to figure out the following error when I tried it. [log.gridtools-clang-20200311a.txt](https://github.com/GridTools/gridtools/files/4318642/log.gridtools-clang-20200311a.txt)

**Comment by havogt** [comment]
From the logs it seems you are using the master branch of GridTools which is not released yet. I'd propose to use the [latest release v1.1.3](https://github.com/GridTools/gridtools/releases/tag/v1.1.3).

**Comment by fthaler** [comment]
This looks like the log of the HCC-based hipcc? This is known to fail. Please try the Clang-based hipcc, but not Clang directly (i.e. hipcc built like this: https://github.com/ROCm-Developer-Tools/HIP/blob/master/INSTALL.md#hip-clang).

**Comment by paklui** [comment]
I want to clarify that the hipcc run that I showed is clang-based hipcc. I rerun it to confirm that I see the similar error in finding the bytecodes:
[log.gridtools-clang-20200311b.txt](https://github.com/GridTools/gridtools/files/4318960/log.gridtools-clang-20200311b.txt)

I'll try the suggestion to use the latest release based on v1.1.3. Thanks.

**Comment by paklui** [comment]
Just want to report that I also see the same issue in v1.1.3.
[log.gridtools-clang-20200311c.txt](https://github.com/GridTools/gridtools/files/4318990/log.gridtools-clang-20200311c.txt)

**Comment by fthaler** [comment]
I am currently building a recent HIP-Clang and will try to reproduce once it’s ready.

**Comment by paklui** [comment]
ok thanks @fthaler let me know if you are able to reproduce. I am using ROCm 3.1 with MI50. I can provide access if you need to a system to the issue,

**Comment by fthaler** [comment]
GridTools (1.1.3) failed compiling here with current LLVM/Clang master due to an internal thrown assertion in the compiler. But I am still able to compile GridTools without problems with my old HIP-Clang version from last September. I will try again with some different versions of LLVM/Clang and see if I can get to something more useful for you…

**Comment by paklui** [comment]
Yes, would appreciate it if you can find out for me. If you have a particular tag/branch or has a hash rev of the LLVM clang that you use I would want to use that version.

**Comment by fthaler** [comment]
So, I finally managed to get a working combination of things:
LLVM:
repo: https://github.com/llvm/llvm-project
commit (branch: release/10.x): 4e41127f04d7d7c6536f78ccdc7e4841a06102ba
ROCm device libs:
repo: https://github.com/RadeonOpenCompute/ROCm-Device-Libs
commit (branch: amd-stg-open): fea23ca22221ef2228d043d2e6b8ab00c8b8d60d
HIP:
repo: https://github.com/ROCm-Developer-Tools/HIP
commit (branch: master): 0726abf424783795c59fadc2e8ba8d80032b6c73
I had to modify one line (https://github.com/ROCm-Developer-Tools/HIP/blob/0726abf424783795c59fadc2e8ba8d80032b6c73/include/hip/hcc_detail/device_functions.h#L41) to make the thing work (just add `template<class... All>`), but that was it then. Builds whole GridTools for me now (tested v1.1.3).

**Comment by paklui** [comment]
Good info. Thanks and I'll give it a try.

**Comment by paklui** [comment]
Thanks alot @fthaler! your suggestion works!!
