### ISSUE TITLE
Add icosahedral stencils support to cpu_ifirst backend

### ISSUE THREAD

**Issue by anstaf** [GridTools/gridtools#1458]
The only thing is needed is to respect colour dimension during the creation of the temporaries.

**Comment by havogt** [comment]
If it is very simple, let's do it otherwise don't. As you know, I don't expect we will ever need it...

**Comment by havogt** [comment]
We will not do it immediately, but if we have some spare cycles and it is really trivial we will do it. Not targeted for GT 2.0 at this point.

**Comment by havogt** [comment]
Closing, as we will most likely never need it...
