### ISSUE TITLE
Parametrize mc and x86 on thread_pool concept

### ISSUE THREAD

**Issue by anstaf** [GridTools/gridtools#1463]
At a moment `mc` and `x86` backends use `OpenMP`only for distributing the tasks between threads. Conceptually it needs just a thread pool. In https://github.com/GridTools/gridtools/pull/1437 new backends are introduced that are algorithmically are the same as `x86` and `OpenMP` but use HPX for the thread pool implementation.

Proposal:
  - define thread pool concept
  - provide its `omp` and `hpx` implementation (maybe pure `pthread` as well? )
  - `mc` and `x86` should be templated on thread pool

Motivation:
- some libraries are incompatible with `omp`, some compilers doesn't have `omp support`. if the users want to use gridtools in that environment we should provide the option.

**Comment by havogt** [comment]
It doesn't break API if we introduce this after GT 2.0, right?

**Comment by anstaf** [comment]
The only API change would be that `::gridtools::mc::backend` would be not a `struct` but `template struct`. So users should use `mc<>` or `mc<alternative_thread_pool>` instead of `mc`.
`x86` is already a `template`.
