### ISSUE TITLE
Rename Jenkins environments

### ISSUE THREAD

**Issue by havogt** [GridTools/gridtools#1469]
clang_nvcc -> clang_cuda
clang -> nvcc_clang

keep:
nvcc_gcc

**Comment by havogt** [comment]
done

**Comment by anstaf** [comment]
There are still old name scheme artifacts in our codebase: `gridtools/jenkins/daint_clang_nvcc.sh` and so on.

**Comment by havogt** [comment]
Ups sorry. I was sure we did it already...
