### ISSUE TITLE
Show an error for overlapping intervals

### ISSUE THREAD

**Issue by lukasm91** [GridTools/gridtools#1487]
Intervals in stage definitions can overlap; no error is detected, and it does _something_. It's unclear to me what it does, but this is clearly illegal.

It would be valuable if we could detect this because it's very likely that people stumble across this problem and get incorrect results for unknown reasons. No priority though, of course, I just open an issue such that it is noted somewhere...

**Comment by havogt** [comment]
Sounds like the evil brother of #29.

**Comment by lukasm91** [comment]
Yes you're right. Sounds like https://github.com/GridTools/gridtools/issues/29#issuecomment-464729326 - I am impressed that you remember this issue. So I think then we can close this one if you agree.

**Comment by havogt** [comment]
It's not hard to remember our oldest issue. Also we went through all issues recently to check which ones go into GT 2.0. ;)

**Comment by havogt** [comment]
Though, I didn't remember my comment. :)
