### ISSUE TITLE
Compiler-option error when building CUDA backend

### ISSUE THREAD

**Issue by chuckyount** [GridTools/gridtools#1494]
I'm getting the following error trying to build the MC and CUDA backends for version 1.1:

$ git status
\# On branch release_v1.1
$ icc -v
icc version 19.1.1.217 (gcc version 8.2.0 compatibility)
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Apr_24_19:10:27_PDT_2019
Cuda compilation tools, release 10.1, V10.1.168
$ mkdir build
$ cd build
$ cmake -DCMAKE_C_COMPILER=icc -DCMAKE_CXX_COMPILER=icpc -DCMAKE_Fortran_COMPILER=ifort -DGT_ENABLE_BACKEND_MC=ON -DGT_ENABLE_BACKEND_CUDA=ON -DCMAKE_INSTALL_PREFIX=$HOME -DGT_INSTALL_EXAMPLES=ON ..
$ cmake --build . -v
...
gmake[2]: Entering directory `/.../gridtools/build'
[  1%] Building CUDA object regression/CMakeFiles/shallow_water_enhanced_cuda.dir/shallow_water_enhanced.cu.o
cd /nfs/pdx/home/cyount/github/gridtools/build/regression && /usr/local/cuda-10.1/bin/nvcc  -DBOOST_PP_VARIADICS=1 -DCPP_BINDGEN_GT_LEGACY -DFUSION_MAX_MAP_SIZE=20 -DFUSION_MAX_VECTOR_SIZE=20 -DGCL_GPU -DGCL_MPI -DGT_BACKEND_CUDA -DGT_FLOAT_PRECISION=8 -DGT_USE_GPU -I/.../gridtools/include -I/usr/local/cuda-10.1/targets/x86_64-linux/include -I/.../gridtools/build/_deps/cpp_bindgen-src/include -isystem=/.../gridtools/build/_deps/googletest-src/googletest/include -isystem=/.../gridtools/build/_deps/googletest-src/googletest -isystem=/.../local/boost_1_68_0 -isystem=/opt/intel/compilers_and_libraries_2020.1.217/linux/mpi/intel64/include  -Xcompiler -pthread --expt-relaxed-constexpr -arch=sm_35 **-qopt-subscript-in-range -qoverride-limits** -diag-disable=15518,15552 -std=c++14 -x cu -c /.../gridtools/regression/shallow_water_enhanced.cu -o CMakeFiles/shallow_water_enhanced_cuda.dir/shallow_water_enhanced.cu.o
** nvcc fatal   : Unknown option 'qopt-subscript-in-range'**

The problem seems to be that it's passing "-qopt-subscript-in-range -qoverride-limits -diag-disable=15518,15552" to nvcc, but I believe those are Intel compiler options. I'm trying to use nvcc 10.1 for the CUDA backend and the Intel compilers (icc, icpc, ifort) for the MC backend.
Any workaround?

**Comment by havogt** [comment]
I opened a PR which should fix this issue, see #1496. We will release this fix soon in GridTools v1.1.4.

Note that we never tried to compile CUDA code with Intel as host compiler and therefore don't recommend it. Also note that we don't have the Intel compiler in our regression suite.

Nevertheless, compiling the mc backend seems to work with `icpc (ICC) 19.1.0.166 20191121`. (It doesn't work with `icpc (ICC) 19.0.1.144 20181018`.) I couldn't verify the cuda backend as my cuda version doesn't support 19.1.

**Comment by chuckyount** [comment]
Great--thanks for the quick response. Will give it a try.

**Comment by chuckyount** [comment]
BTW, your message says that you don't recommend the Intel compiler for the host compiler. Is there a way to configure GridTools's cmake to build the MC backend w/icpc and use gcc as the CUDA host compiler?

**Comment by havogt** [comment]
GridTools is a header-only library (except for a single file), so building mc and cuda means building the tests. The cleanest setup would be to use 2 separate builds, one for cuda with nvcc+gcc and one for the cpu backends (mc or x86) with the Intel compiler (actually I would recommend here also to use gcc or clang, but that's probably not the message you would like to hear ;) ).

If you want to try with a mixed build you could try something like 
```
CXX=`which icpc` CUDAHOSTCXX=`which g++` cmake ...
```
But I am not 100% sure if it will work.

**Comment by chuckyount** [comment]
Ok; I gave up on using the Intel compilers and MPI (for now). I'm using gnu 6.3 compilers (gcc, g++, and gfortran), cuda 10.1, and openMPI 1.10.7 on RHEL 7.3. Finally got all the tests to build. They all pass except `test_halo_exchange_3D_*_cuda` and `test_distributed_boundaries_cuda` (11 tests fail). Any pointers on what to look for? The node I'm testing on contains two Tesla V100 GPUs. (Are 2 GPUs supported?)

**Comment by havogt** [comment]
I'll close this issue as the original problem (forwarding flags to nvcc) is resolved in the v1.1 branch.

**Comment by chuckyount** [comment]
FYI, to get the tests to build correctly, I had to explicitly specify the gnu compilers. Otherwise, cmake found other tools on my system that did not work. I used this config cmd:
`cmake -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_Fortran_COMPILER=gfortran -DGT_ENABLE_BACKEND_MC=ON -DGT_ENABLE_BACKEND_CUDA=ON -DCMAKE_INSTALL_PREFIX=$HOME -DGT_INSTALL_EXAMPLES=ON ..`
in case you want to add it to a FAQ list.

**Comment by havogt** [comment]
Thanks, I added a short description to the README in #1502
