### ISSUE TITLE
Seg fault when running CUDA halo-exchange tests

### ISSUE THREAD

**Issue by chuckyount** [GridTools/gridtools#1499]
Just trying to build and run tests.
I'm using gnu 6.3 compilers (gcc, g++, and gfortran), cuda 10.1, and openMPI 1.10.7 on RHEL 7.3. Finally got all the tests to build. They all pass except `test_halo_exchange_3D_*_cuda` and `test_distributed_boundaries_cuda` (11 tests fail). Any pointers on what to look for? 
Example output: https://pastebin.com/SLpMeVwQ (looks like a segv).

The node I'm testing on contains two Tesla V100 GPUs. (Are 2 GPUs supported?) Which raises the question: what happens when testing halo exchange on a GPU? If there are 4 MPI ranks on the same machine, do all 4 try to use the same GPU?

**Comment by chuckyount** [comment]
I tried specifying the GPU device per rank, but that didn't help:
`$ mpirun -np 1 -x CUDA_VISIBLE_DEVICES=0 ./unit_tests/communication/test_halo_exchange_3D_all_cuda : -np 1  -x CUDA_VISIBLE_DEVICES=1 ./unit_tests/communication/test_halo_exchange_3D_all_cuda
 2
out1.txt
*** test output for rank 0 of 2

  TEST  Communication::test_halo_exchange_3D_all
0 2
out0.txt
--------------------------------------------------------------------------
mpirun noticed that process rank 1 with PID 107953 on node ortce-skl6 exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------
`

**Comment by havogt** [comment]
Is your MPI implementation CUDA-aware?

**Comment by mbianco** [comment]
I think OpenMPI supports CUDA since version 1.7. That was quite some time ago but should work. Latest version OpenMPI version 4 is the latest available. The MPI library should be compiled with `--with-cuda=${CUDA_HOME}` option. You can check if the MPI implementation you have is GPU-aware, this command could work: `ompi_info --parsable --all | grep mpi_built_with_cuda_support:value`

**Comment by chuckyount** [comment]
What MPI package do you recommend? I don't see it in the README.

**Comment by chuckyount** [comment]
Looks like the version I installed via yum doesn't support CUDA:
`mca:mpi:base:param:mpi_built_with_cuda_support:value:false
mca:mpi:base:param:mpi_built_with_cuda_support:source:default
mca:mpi:base:param:mpi_built_with_cuda_support:status:read-only
mca:mpi:base:param:mpi_built_with_cuda_support:level:4
mca:mpi:base:param:mpi_built_with_cuda_support:help:Whether CUDA GPU buffer support is built into library or not
mca:mpi:base:param:mpi_built_with_cuda_support:enumerator:value:0:false
mca:mpi:base:param:mpi_built_with_cuda_support:enumerator:value:1:true
mca:mpi:base:param:mpi_built_with_cuda_support:deprecated:no
mca:mpi:base:param:mpi_built_with_cuda_support:type:bool
mca:mpi:base:param:mpi_built_with_cuda_support:disabled:false
`

**Comment by chuckyount** [comment]
Seems I'll have to build my own version of OpenMPI, since all versions provided via `yum` don't seem to have CUDA support. Just a suggestion: add MPI requirements to your README.

**Comment by havogt** [comment]
Thanks, I added MPI to the list of requirements in #1502.

**Comment by havogt** [comment]
Closing, as no further action is required as far as I can see. Please re-open if you have further questions or open a new issue for follow-up problems.
