### ISSUE TITLE
Support the Intel compiler with -qnextgen

### ISSUE THREAD

**Issue by havogt** [GridTools/gridtools#1503]
We dropped the workarounds for Intel in GridTools 2.0, hoping that the LLVM-based Intel compiler (`-qnextgen`) will work. With Intel 19.1.0.166 (available on dom), GT 2.0 doesn't compile. I didn't try to investigate. Maybe we should have a look and decide if we can support it.

**Comment by chuckyount** [comment]
Just FYI and FWIW: I was also unable to build GT 2.0 with Intel nextgen compiler that ships with Version 19.1.0.166 (Build 20191121), but I _was_ able to build with Version 19.1.1.217 (Build 20200306), so perhaps you can give it another try when you get the newer version.

**Comment by havogt** [comment]
Cool, thanks for the input!

**Comment by havogt** [comment]
I was able to verify now with `19.1.1.217`.

**Comment by chuckyount** [comment]
FYI, the release model for the new Intel compilers has changed. In the new model, the LLVM-based C++ compiler is launched via `icpx`, not `icpc -qnextgen`. See https://software.intel.com/content/www/us/en/develop/articles/porting-guide-for-icc-users-to-dpcpp-or-icx.html

**Comment by havogt** [comment]
Thanks! I'll close this issue.
