### ISSUE TITLE
Implement `int_vector` library

### ISSUE THREAD

**Issue by anstaf** [GridTools/gridtools#1669]
# Motivation
`fn` needs an API to manipulate offsets, sizes and extents.

# The Library:
Let us define `int_vector` as a `hymap` which value types are all either of integral types or of integral constant types (`is_integral_constant`). Additionally `std::trivially_copy_constructible` is probably needed to be able to pass such a vectors to CUDA kernel.

## Meta part: (requires https://github.com/GridTools/gridtools/issues/1668)
  * `is_int_vector<T>` type trait  
  * `concepts::int_vector<T>` predicate

## RT part (probably everything should be __host__ __device__ (aka GT_FUNCTION)):
  * `plus`  -- a function that takes two `int_vector`'s and return an `int_vector`. The dimensions (keys) of the result is the the union of the arguments keys. 
  * `multiply` -- a function that accepts an `int_vector` and a scalar (integral or integral_constant) and returns an `int_vector`
  * `normalize`  -- a function that takes an`int_vector` and removes dimensions which values are equal to `0_c` 

### Syntax sugar
We can define `+`, `-`, unary `-` , `*` and `/`  operators on the top of `plus` and `multiply`. They should be SFINAE enabled and located in a separate namespace (so that the user can explicitly `opt in`/`opt out` them).

**Comment by anstaf** [comment]
# Correction
`gridtools::is_integal_constant` checks that the class is derived from `std::integral_constant` instantiation.
In practice we need more -- Arithmetic operators need to be overloaded and CUDA enabled. This is what `gridtools::integral_constant` provides.
# Proposal
Let us add additional predicate: `gridtools::is_gr_integral_constant` that checks that the class is derived from `gridtools::integral_constant` instantiation. We will use that predicate in defining `is_int_vector` predicate

**Comment by anstaf** [comment]
# a note on enabling `host/device` 
In gridtools there are two ways of doing that:
* simple -- just prefix all your (template) functions with `GT_FUNCTION`;
* complex -- using CPP preprocessing mechanism for generating separate namespaces.

Each time it is a design choice and there are trade offs:
 * `simple way` is good because it is easy to implement and  fast to compile; 
 * there are cases where the `simple way` just doesn't work:
   ```c++
   struct foo { void call_me() { /* uses some host specific API */}  };  
   struct bar { GT_FUNCTION void call_me() {}  };
   template <class T> void baz(T x) { x.call_me(); }
   void host_fun() { baz(foo{}); }
   __global__ void a_kernel() { baz(bar{}); }
   ```
Rationales for Gridtools design choices:
  * `tuple_util` and `for_each` uses the complex way because we want to use it in both host/device contexts and instantiations are context sensible.
  *  gridtools::integral_constant` uses the simple way because nothing can go wrong -- instantiations can not call host only code by design.
  * `gridtools::tuple` uses the simple way. This works without problems if the tuple is instantiated with trivial types (or the types where ctor/dtors are host/device enabled) but it creates problems with `gridtools::tuple<std::string>` for example. 
  * `hymap` free functions and utilities use the complex way but `hymap::keys` uses the simple one.
  * `sid` concept assumes that some functions are host device (like `shift` and `deref`) and some are intentionally host only (like `get_strides`, `get_origin`). Hence everything is implemented in a simple way because contexts are not mixed.

Taking all of that into account I would suggest to implement host/device for int_vectors in a simple way. Because we already have done this choice for `hymap::keys`  and `integral_constants`

**Comment by fthaler** [comment]
I don’t like the naming choice of the `normalize` function as often normalizing a vector means transforming it to a unit vector pointing into the same direction. I would propose `nonzeros` as an alternative.
