### ISSUE TITLE
fatal error: stdlib.h: No such file or directory

### ISSUE THREAD

**Issue by fometeo** [GridTools/gridtools#1705]
nevertheless the file exists at
/usr/include/boost/cstdlib.hpp
/usr/include/boost/nowide/cstdlib.hpp
/usr/include/bsd/stdlib.h
/usr/include/c++/11/stdlib.h
/usr/include/c++/11/tr1/stdlib.h
/usr/include/freetype2/freetype/config/ftstdlib.h
/usr/include/stdlib.h
/usr/include/x86_64-linux-gnu/bits/stdlib.h

I get this error at make stage:

[  3%] Building CXX object tests/src/CMakeFiles/regression_main.dir/regression_main.cpp.o
In file included from /root/setup/gridtools-release_v2.1/tests/include/test_environment.hpp:12,
                 from /root/setup/gridtools-release_v2.1/tests/src/regression_main.cpp:10:
/usr/include/c++/11/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
   75 | #include_next <stdlib.h>
      |               ^~~~~~~~~~
compilation terminated.

**Comment by fometeo** [comment]
version 2.1 compiles OK at Ubuntu 20.04.4 LTS, sorry I do not mentioned the fatal error: stdlib.h: No such file or directory happens at Ubuntu 22.04 daily 2022-03-13, (?) I do not understand this 8-]

**Comment by mbianco** [comment]
Hi @fometeo , this seems to me a problem related to `#include_next`, which is described here: https://gcc.gnu.org/onlinedocs/cpp/Wrapper-Headers.html . Include next search for the next file after the first one which is found by regular `include` (the one that you see in your filesystem). To prove this you can try to hack it by changing the `include_next` into an `include` and see what happens.

**Comment by fometeo** [comment]
Hi @mbianco , yes seems so, thank you. It seems to expect files at /usr/local/include
cp /usr/include/stdlib.h /usr/local/include
cp /usr/include/math.h /usr/local/include
nevertheless make fails with a long set of other errors, anyway Ubuntu 22.04 is still not ready.

**Comment by havogt** [comment]
I'll close as this is unlikely an error of gridtools, but a problem of the environment.
