### ISSUE TITLE
compilation of gridtools fails on VM with CUDA12.0

### ISSUE THREAD

**Issue by avocino** [GridTools/gridtools#1801]
Hi, I am trying to compile gridtools inside a docker running on EWC (nvidia vGPU with CUDA12.0, OS rocky linux 9.4, gcc 11.4.1 and ompi cuda-aware through ucx).
I attach the log of cmake and make, the latter with errors.
Thank you in advance for your support or any hints.
Antonio
[cmake.log](https://github.com/user-attachments/files/16414166/cmake.log)
[make.log](https://github.com/user-attachments/files/16414167/make.log)

**Comment by fthaler** [comment]
Hi and thanks for reporting the issue!

I could not reproduce the problem on our side. Looks like for some reason, a required macro definition that should be generated by CMake is missing when compiling that test.

What is your CMake version? And what’s the output of `make clean && make VERBOSE=1 layout_transformation_test_cpu`?

If possible, you could also share your Dockerfile, this might help us debugging.

**Comment by avocino** [comment]
Hi Felix, thank you for your prompt support.
cmake version 3.26.5
attached log of make as requested
attached Dockerfile as well
thanks a lot in advance

PS: after cmake and before make I forced to load CUDA language putting a row "enable_language(CUDA)" at the row #173 in the cmake file:
build/CMakeFiles/build-install/lib/cmake/gridtools_setup_targets.cmake
here attached with this modification. without that I have got a GPU NOT FOUND message..

[make1.log](https://github.com/user-attachments/files/16423226/make1.log)
[Dockerfile_gt.TXT](https://github.com/user-attachments/files/16423302/Dockerfile_gt.TXT)
[gridtools_setup_targets.cmake.TXT](https://github.com/user-attachments/files/16423305/gridtools_setup_targets.cmake.TXT)

**Comment by fthaler** [comment]
Thank you, the Dockerfile was especially useful, I could easily reproduce your issue now. This actually seems to be a bug of the specific CMake version. If you upgrade to a newer version (e.g., just downloads and install the binaries from [https://cmake.org/download](https://cmake.org/download)), everything works as expected (same for older versions).
You should not have to change any CMake file either, things should work out of the box. E.g., in your container I just did `MPI_HOME=/usr/local/mpi /path/to/newer/cmake /path/to/gridtools` and everything builds fine over here.

Please let me know if this indeed fixes your issues.

**Comment by avocino** [comment]
thanks!!! please clarify this point:
setting in the container
MPI_HOME=/usr/local/mpi /path/to/newer/cmake /path/to/gridtools
why?

**Comment by DropD** [comment]
This would be the command you can use in the container to build GridTools.
`MPI_HOME=/usr/local/mpi` tells cmake where to find `MPI`, `/path/to/newer/cmake /path/to/gridtools` runs the appropriate `CMake` version inside the gridtools folder.

**Comment by avocino** [comment]
now the compilation completes, but I still see the GPU mode not found at row #165 in the log file attached

[make2.log](https://github.com/user-attachments/files/16425878/make2.log)

**Comment by avocino** [comment]
> This would be the command you can use in the container to build GridTools. `MPI_HOME=/usr/local/mpi` tells cmake where to find `MPI`, `/path/to/newer/cmake /path/to/gridtools` runs the appropriate `CMake` version inside the gridtools folder.

ok, you just mean that the dockerfile can be easily adapted to build gridtools automatically... no problem for that ;-)

**Comment by avocino** [comment]
> now the compilation completes, but I still see the GPU mode not found at row #165 in the log file attached
> 
> [make2.log](https://github.com/user-attachments/files/16425878/make2.log)

by the way, the testing FAILS for a few tests as from the log attached, please let me know if it is already known or to be fixed

[LastTest.log](https://github.com/user-attachments/files/16426307/LastTest.log)

**Comment by fthaler** [comment]
> now the compilation completes, but I still see the GPU mode not found at row #165 in the log file attached
> 
> [make2.log](https://github.com/user-attachments/files/16425878/make2.log)

The output you see here is from a test that checks the CMake setup and compilation of an example in the documentation. That is, the output comes from a separte CMake run which does not have to bother you. As long as your CMake config step has detect GPU support, everything is fine.


> > now the compilation completes, but I still see the GPU mode not found at row #165 in the log file attached
> > [make2.log](https://github.com/user-attachments/files/16425878/make2.log)
> 
> by the way, the testing FAILS for a few tests as from the log attached, please let me know if it is already known or to be fixed
> 
> [LastTest.log](https://github.com/user-attachments/files/16426307/LastTest.log)

Most of the failures seem to be due to running mpiexec as root (which is probably normal inside Docker and you should be able to fix it by passing `--allow-run-as-root` to mpiexec, e.g. by passing `cmake -DMPIEXEC_PREFLAGS=--allow-run-as-root ...` in the configuration step). The remaining failures are a bit more suspicious, but probably nothing you have to worry about.

**Comment by avocino** [comment]
> The output you see here is from a test that checks the CMake setup and compilation of an example in the documentation. That is, the output comes from a separte CMake run which does not have to bother you. As long as your CMake config step has detect GPU support, everything is fine.

OK, but it is confusing, especially newbies...

**Comment by avocino** [comment]
> Most of the failures seem to be due to running mpiexec as root (which is probably normal inside Docker and you should be able to fix it by passing `--allow-run-as-root` to mpiexec, e.g. by passing `cmake -DMPIEXEC_PREFLAGS=--allow-run-as-root ...` in the configuration step). The remaining failures are a bit more suspicious, but probably nothing you have to worry about.

ok, now just 2 tests fail, namely:
186 - test_hugepage_alloc (Failed)
263 - test_shared_allocator (Failed)
I hope that as you suggested this has not any impact on COSMO model compilation.. please let me know

warm thanks,
antonio

**Comment by fthaler** [comment]
> > The output you see here is from a test that checks the CMake setup and compilation of an example in the documentation. That is, the output comes from a separte CMake run which does not have to bother you. As long as your CMake config step has detect GPU support, everything is fine.
> 
> OK, but it is confusing, especially newbies...

I agree :)


> > Most of the failures seem to be due to running mpiexec as root (which is probably normal inside Docker and you should be able to fix it by passing `--allow-run-as-root` to mpiexec, e.g. by passing `cmake -DMPIEXEC_PREFLAGS=--allow-run-as-root ...` in the configuration step). The remaining failures are a bit more suspicious, but probably nothing you have to worry about.
> 
> ok, now just 2 tests fail, namely: 186 - test_hugepage_alloc (Failed) 263 - test_shared_allocator (Failed) I hope that as you suggested this has not any impact on COSMO model compilation.. please let me know
> 
> warm thanks, antonio

That looks OK to me.
In the worst case the first failure might minimally affect CPU performance, but should not functionally relevant. For GPUs this doesn’t matter at all. We had some failure there before, where some compilers optimize unexpected things away. I’ll try to reproduce and fix if I find some time.
The second failure looks like your setup does not support `cudaMallocManaged` for some reason. But this is only used inside this specific test, so shouldn’t be relevant for anything else either.

**Comment by avocino** [comment]
great! thanks again, issue closed by my side
cheers
Antonio

**Comment by fthaler** [comment]
Perfect!
Cheers, Felix

**Comment by havogt** [comment]
The version compatible with COSMO is v2.0.0. See https://github.com/COSMO-ORG/cosmo/blob/838095d766f5820a8cb160b49548c6c5123ad989/dycore/CMakeLists.txt#L36. Later versions are not tested and if I remember correctly, there is an incompatibility with later versions (maybe only in tests).

**Comment by avocino** [comment]
Dear Felix, sorry to bother you. I am not able to open the link about cosmo installation under COSMO-ORG (for restricted access I argue, but I was able in the past), may I ask you the contact person for the authorization? I would have a look at cosmo dycore (and last cosmo v6 as well).
thanks a lot Antonio
