### ISSUE TITLE
Temporary storage size in k

### ISSUE THREAD

**Issue by havogt** [GridTools/gridtools#491]
Before PR #490 the k size of temporaries is wrong: only the value of the splitter is used but the offsets are not taken into account. The quick fix there is to use the size defined by the axis.

The disadvantage is that in the dycore we allocate to much memory because the axis is a global property and only a few stencils use the full axis.

Possible solutions:

1. The size of the k-interval for the computation is computed somewhere in the intermediate, I guess. This value could be used instead of the axis.
2. The first approach approach still allocates too much memory in case the temporary is only used in parts of the k-interval of the computation. The STELLA approach is to pass the interval as a template parameter to the temporary.

**Comment by anstaf** [comment]
fixed in v1.1
