### ISSUE TITLE
out of bounds in accessor

### ISSUE THREAD

**Issue by cosunae** [GridTools/gridtools#554]
we can define 
```
using pp = accessor< 0, enumtype::in, extent< 0, 1, 0, 1 > >
eval(pp(0,2,0,1) );
``` 
Which is wrong. There are checks that the index computed does not going beyond the size of the storage. But if the size of storage were large enough, is not going to trigger any error. 

In case offset_tuple were built as a constant expression, like here (and most of the cases) we could build a compile time protection.

**Comment by anstaf** [comment]
fixed in PR #1417
