### ISSUE TITLE
add lost check_grid_against_extents feature

### ISSUE THREAD

**Issue by stefanmoosbrugger** [GridTools/gridtools#665]
@mbianco reported that the `check_grid_against_extents` in the `intermediate` ctor got lost when integrating the new storage. This check should be added again. See https://github.com/eth-cscs/gridtools/blob/552574a6a7dea2e59fce957648e84b9905e29419/include/stencil-composition/intermediate.hpp#L460 for the implementation.

**Comment by anstaf** [comment]
fixed in PR #1417
