### ISSUE TITLE
Is a compilation error excessive for selecting Host backend?

### ISSUE THREAD

**Issue by mbianco** [GridTools/gridtools#729]
Currently we cannot instantiate a stencil on the host in the same translation unit as a GPU stencil.
This may be a little to conservative.

https://github.com/eth-cscs/gridtools/blob/master/include/stencil-composition/backend_base.hpp#L122

We agreed that we should have some sort of warning/message when this happens (maybe in debug mode for instance), but it's not clear now how to do it. Some thoughts?

**Comment by anstaf** [comment]
resolved (probably already in v1.1)
