### ISSUE TITLE
Storage fixes collection

### ISSUE THREAD

**Issue by havogt** [GridTools/gridtools#809]
When actively using the new storage module in the past month we discovered several short comings. In today's meeting we decided that it would be good to have a discussion in the next sprint planning about the use-cases (e.g. Atlas, c-bindings, ...) and discuss how to make the design cleaner (e.g. mixing data_stores with external ptr or allocated memory into one type) and fix the issues. In this issue we collect these short-comings and possible solutions.

# Empty data_stores, data_views

## data_store

Current design: It is possible to construct an empty data_store (only the name is set), where the `shared_ptr`s for `storage` and `storage_info` are `nullptr`s. The allocation will then happen on `allocate()`.

Source of this requirement: Atlas and the c-bindings have patterns where the size of the data_store is only known after construction.

Problem: The design is confusing as there are conditions when the user has do to ctor+allocate or just ctor.

We discussed 2 Possible solutions:
a) **Make the data_store more like a std container with mutable size:** Instead of creating the shared_ptr's with `nullptr` we could allow the storage to have size 0. The `allocate()` would be replaced by `resize()` which would do proper copying if the data_store size is increased.
Solution of the problem: the data_store is *always* in an initialized state (though the storage could have size 0).
b) **The data_store doesn't need the resize mechanism (i.e. has only two states: allocated/non-allocated):** In this case the best pattern would probably be to use `boost::optional` (or `std::optional` if possible) on the "user"-side (where user = Atlas or the c-binding module) as it clearly describes that this data_store can be in a non-initialized state.
Solution of the problem: the data_store is always initialized.

# External ptr data_stores

Current design: The data_store supports to allocate memory or use an external pointer.

Problem: The implementation mixes the concept of external ptr and allocated memory and manages a state.

Possible solution: Split the two cases into separate classes with a common interface (runtime inheritance as it is not performance critical). Details and impact needs to be investigated.

# Alignment 

See #790.

# Define user API for data_store, storage_info, data_view

Problem: Different requirements showed up which where adding new methods to access information like dimension, etc. We should cleanup and try to define which class should provide which information.

**Comment by anstaf** [comment]
resolved in v2.0 (and earlier)
